name: 5.$(Date:yy).$(Date:MMdd)$(Rev:.rr)

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      sudo apt-get install zip
      sudo npm i yarn -g
      sudo chown -R $USER:$GROUP ~/.npm
      sudo chown -R $USER:$GROUP ~/.config

  - task: Bash@3
    inputs:
      filePath: "build.sh"
      arguments: $(Build.BinariesDirectory) $(Build.Repository.LocalPath)
      workingDirectory: "$(Build.Repository.LocalPath)"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.BinariesDirectory)"
      Contents: "**"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish build artifacts"
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/dev')))
